#!/bin/bash
# 8B non-thinking DAPO + branch_adv on DAPO-Math-17k.
#
# Reference invocation:
#   bash examples/run_multinode_1_02_20_2k_4k_dapo.sh \
#     --model_path /mnt/public/users/liuwenpu/model/Qwen/Qwen3-8B \
#     --train_data /mnt/public/users/liuwenpu/data/DAPO-Math-17k-Processed/train.parquet \
#     --val_data   /mnt/public/users/liuwenpu/data/val_merge/val_merged.parquet \
#     --task_name  8b_non_thinking_04_30_20_wo_format_17k \
#     --output_path /path/to/local/ckpt \
#     --gpus 8 \
#     --max_prompt_length 2048 \
#     --max_response_length 8192 \
#     --config_path examples/config_2k-8k_wo_format_04_03_20.yaml \
#     --swanlab_project new_math-2k-4k \
#     --swanlab_mode cloud
#
# Notes:
#   - train/val parquet point at the *.formatted.parquet (jinja pre-rendered,
#     val rows tagged extra_info.split='val'). Generated by:
#       python3 examples/branch_adv/preprocess_parquet.py ...
#   - output_path moved under EDPO/verl/ckpt.
#   - --config_path is accepted by run_dapo_branch_adv.sh for parity but
#     ignored; verl uses recipe/dapo/config/dapo_trainer.yaml + Hydra overrides.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERL_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${VERL_ROOT}"

bash examples/branch_adv/run_dapo_branch_adv.sh \
  --model_path /mnt/public/users/liuwenpu/model/Qwen/Qwen3-8B \
  --train_data /mnt/public/users/liuwenpu/data/DAPO-Math-17k-Processed/train.formatted.parquet \
  --val_data   /mnt/public/users/liuwenpu/data/val_merge/val_merged.formatted.parquet \
  --task_name  8b_non_thinking_04_30_20_wo_format_17k \
  --output_path /mnt/public/users/liuwenpu/EDPO/verl/ckpt \
  --gpus 8 \
  --max_prompt_length 2048 \
  --max_response_length 8192 \
  --swanlab_project new_math-2k-4k \
  --swanlab_mode cloud \
  "$@"
